app/models/duvida.py
from flask_sqlalchemy import SQLAlchemy
from app.__init__ import db

class Duvida (db.Model):
    __tablename__ = 'duvida' 
    id = db.Column(db.Integer, primary_key = True, autoincrement = True)
    titulo = db.Column(db.String(80), nullable = False)
    descricao = db.Column(db.String(80), nullable = True)
    id_usuario =db.Column(db.Integer, db.ForeignKey('usuario.id'), nullable = True)

    usuario = db.relationship('Usuario', backref='duvida', lazy=True)


    

app/routes/adm.py
from flask import Blueprint, render_template, redirect, request, url_for
from app.models.usuario import Usuario
from app.models.petiscoCachorro import PetiscoCachorro
from app.models.petiscoGato import PetiscoGato
from app.models.brinquedo import Brinquedo
from app.models.duvida import Duvida
from app.__init__ import db

admBlueprint = Blueprint("adm", __name__, url_prefix="/adm")

@admBlueprint.route("/")
def home():
    return render_template("rotaADM.html")

@admBlueprint.route('/listar', methods = ['GET'])
def listar():
    usuarios = Usuario.query.all()
    produtosCachorro = PetiscoCachorro.query.all()
    produtosGato = PetiscoGato.query.all()
    produtosBrinquedo = Brinquedo.query.all()
    duvidas= Duvida.query.all()

    return render_template("listarTudo.html", usuarios = usuarios, produtosCachorro = produtosCachorro, produtosGato = produtosGato, produtosBrinquedo = produtosBrinquedo, duvidas = duvidas)

app/routes/home.py
from flask import Blueprint, render_template, redirect, request, url_for, flash
from app.models.duvida import Duvida
from app.models.usuario import Usuario
from app.__init__ import db

homeBlueprint = Blueprint('home', __name__)

#rota inicial
@homeBlueprint.route('/', methods = ['GET'])
def home():
    return render_template('index.html')

@homeBlueprint.route('/sobrenos', methods = ['GET'])
def sobreNos():
    return render_template('sobreNos.html')

@homeBlueprint.route('/duvidas')
def duvidas():
    duvidas = Duvida.query.all()
    return render_template('duvidas.html', duvidas = duvidas)

@homeBlueprint.route('/duvida/add', methods = ["POST","GET"])
def addDuvida():
    if request.method == "GET":
        return render_template('addDuvida.html')
    if request.method == "POST":
        titulo = request.form.get('titulo')
        descricao = request.form.get('descricao')
        nome = request.form.get('nome_usuario')

        usuario = Usuario.query.filter_by(nome = nome).first()
        if not nome or not titulo:
           flash("Todos os campos devem ser preenchidos", 'error')
           return redirect(url_for("home.addDuvida"))

        duvida = Duvida(titulo = titulo, descricao = descricao, id_usuario = usuario.id)

        db.session.add(duvida)
        db.session.commit()

        return redirect(url_for('home.home'))

app/routes/produto.py
from flask import Blueprint, render_template, redirect, url_for, Response, request, flash
from app.models.petiscoCachorro import PetiscoCachorro
from app.models.petiscoGato import PetiscoGato
from app.models.brinquedo import Brinquedo
from app.__init__ import db

produtoBlueprint = Blueprint('produto', __name__, url_prefix="/produto")

@produtoBlueprint.route('/', methods = ['GET'])
def home():
    produtosCachorro = PetiscoCachorro.query.all()
    produtosGato = PetiscoGato.query.all()
    produtosBrinquedo = Brinquedo.query.all()

    return render_template("produtos.html", produtosCachorro = produtosCachorro, produtosGato = produtosGato, produtosBrinquedo = produtosBrinquedo)

@produtoBlueprint.route('/add', methods = ['GET','POST'])
def add():
    if request.method == "GET":
        return render_template('addProduto.html')
    elif request.method == 'POST':
        tipo = request.form.get('tipo')
        nome = request.form.get('nome')
        descricao = request.form.get('descricao')
        preco = request.form.get('preco')
        disponivel = request.form.get('disponivel')
        imagem = request.files['imagem']

        if disponivel == "sim":
            disponivel = True
        elif disponivel == "nao":
            disponivel = False

        try:
            float(preco)
        except:
            return ("valor invalido", 400)

        if not nome or not descricao or not preco or not disponivel:
            flash('Todos os campos devem ser preenchidos!', 'error')
            return redirect(url_for('produto.add'))
        
        match tipo:
            case 'brinquedo':
                novo_produto = Brinquedo(nome = nome, descricao = descricao, preco = preco, disponivel = disponivel, imagem = imagem.read())
            case 'petiscoC':
                novo_produto = PetiscoCachorro(nome = nome, descricao = descricao, preco = preco, disponivel = disponivel, imagem = imagem.read())
            case 'petiscoG':
                novo_produto = PetiscoGato(nome = nome, descricao = descricao, preco = preco, disponivel = disponivel, imagem = imagem.read())

        db.session.add(novo_produto)
        db.session.commit()

        print("Funcionou!")

        return redirect(url_for('adm.listar_tudo'))
    
@produtoBlueprint.route('/update/<int:produto_id>', methods = ["GET", "POST"])
def update(produto_id):
    if request.method == "GET":
        return render_template('updateProduto.html') 
    if request.method == "POST":
        try:
            produto = PetiscoCachorro.query.filter_by(id = produto_id).first()
        except:
            try:
                produto = PetiscoGato.query.filter_by(id= produto_id).first()
            except:
                produto = Brinquedo.query.filter_by(id = produto_id).first()
        
        produto
        


@produtoBlueprint.route('/foto/<int:produto_id>', methods = ['GET'])
def foto(produto_id):
    try:
        produto = PetiscoGato.query.get_or_404(produto_id)
    except:
        try:
            produto = PetiscoCachorro.query.get_or_404(produto_id)
        except:    
            produto = Brinquedo.query.get_or_404(produto_id)
            

    if produto.imagem:
        return Response(produto.imagem, mimetype='image/jpeg')
    else:
        # Retornar uma imagem padrão caso não tenha foto
        return redirect(url_for('static', filename='default.png'))

app/routes/usuario.py
from flask import Blueprint, render_template, redirect, request, url_for, flash, Response
from flask_login import login_user, login_required, current_user
from app.models.usuario import Usuario
from app.__init__ import db

usuarioBlueprint = Blueprint('usuario', __name__, url_prefix='/usuario')

@usuarioBlueprint.route('/cadastro', methods = ['GET', 'POST'])
def cadastro():
    if request.method == 'GET':
        return render_template('adicionarUsuario.html')
    elif request.method == 'POST': 
    
        nome = request.form.get('nome')
        email = request.form.get('email')
        senha = request.form.get('senha')
        if not nome or not email or not senha:
            flash("Todos os campos devem ser preenchidos", 'error')
            return redirect(url_for("usuario.cadastro"))
        
        novo_usuario = Usuario(nome = nome, email = email, senha = senha)

        db.session.add(novo_usuario)
        db.session.commit()
        print("Funcionou!")
         
        return redirect(url_for('home.home'))
    
@usuarioBlueprint.route("/update/<int:usuario_id>", methods = ['GET','POST'])
def update(usuario_id):
    if request.method == 'GET':
        usuario = Usuario.query.filter_by(id=usuario_id).first()
        return render_template("updateUser.html", usuario = usuario)
    if request.method == 'POST':
        usuario = Usuario.query.filter_by(id = usuario_id).first()

        nome = request.form.get('nome')
        email = request.form.get('email')
        senha = request.form.get('senha')
        foto_perfil = request.files['foto_perfil']

        if foto_perfil:
            usuario.nome = nome
            usuario.email = email
            usuario.senha = senha
            usuario.foto_perfil = foto_perfil.read()
        else:
            usuario.nome = nome
            usuario.email = email
            usuario.senha = senha

        db.session.commit()

        print("Funcionou!")
        return redirect(url_for('adm.listar'))
    

@usuarioBlueprint.route('/delete/<int:usuario_id>', methods=["POST"])
def delete(usuario_id):
    usuario = Usuario.query.filter_by(id=usuario_id).first()
    if usuario:
        db.session.delete(usuario)
        db.session.commit()
    return redirect(url_for('adm.listar'))


@usuarioBlueprint.route('/foto/<int:usuario_id>', methods = ['GET'])
def foto(usuario_id):
    usuario = Usuario.query.get_or_404(usuario_id)
    if usuario.foto_perfil:
        return Response(usuario.foto_perfil, mimetype='image/jpeg')
    else:
        # Retornar uma imagem padrão caso não tenha foto
        return redirect(url_for('static', filename='default.png'))

@usuarioBlueprint.route('/logar', methods=["GET", "POST"])
def logar():
    if request.method == "GET":
        return render_template('login.html')
    if request.method == "POST":
        email = request.form.get('email')
        senha = request.form.get('senha')
        remember = True if request.form.get('remember') else False

        user = Usuario.query.filter_by(email = email).first()

        if not email or not senha:
            flash("Todos os campos devem ser preenchidos", 'error')
            return redirect(url_for("usuario.logar"))
        
        login_user(user, remember)
        return redirect(url_for('usuario.profile'))
    
@usuarioBlueprint.route('/profile')
@login_required
def profile():
    return render_template('index.html', nome = current_user.nome, logado = True)

app/templates/addDuvida.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='layout.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>Criar cadastro</title>
</head>
<body>
    <header>
        <img src="{{url_for('static', filename='BICHOITO.png')}}" class="bichoito">
        <nav>
            <ul>
                <li><a class="cabecalho" href="{{url_for('home.home')}}">Home</a></li>
                <li><a class="cabecalho" href="{{url_for('home.duvidas')}}">Duvidas</a></li>
                <li><a class="cabecalho" href="{{url_for('produto.home')}}">Produtos</a></li>
                <li><a class="cabecalho" href="about_us.html">Sobre nós</a></li>
                <li><a class="cabecalho" href="{{url_for('usuario.logar')}}">logar</a><img src="{{url_for('static', filename='usuario.jpg')}}" alt="" width="20" height="20"> </li>
                <li><a class="cabecalho" href="{{url_for('adm.home')}}">adm</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <div class="container mt-5">
            <h1>Fazer uma duvida</h1>
            <!-- Exibir mensagens -->
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            <form action="{{url_for('home.addDuvida')}}" method="post">
                <label for="titulo">Escreva aqui a sua duvida</label><br>
                <input type="text" name="titulo" id="titulo"><br><br>

                <label for="descricao">Escreva aqui a descrição que responde a pergunta</label><br>
                <input type="text" name="email" id="email"><br><br>

                <label for="nome_usuario">Nome do usuario</label><br>
                <input type="text" name="nome_usuario" id="nome_usuario"><br><br>

                <button type="submit" class="btn btn-primary">cadastrar</button>

            </form>
        </div>
    </main>
</body>
</html>

app/templates/addProduto.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='layout.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>ADD PRODUTOS</title>
</head>
<body>
    <header>
        <img src="{{url_for('static', filename='BICHOITO.png')}}" class="bichoito">
        <nav>
            <ul>
                <li><a class="cabecalho" href="{{url_for('home.home')}}">Home</a></li>
                <li><a class="cabecalho" href="{{url_for('home.duvidas')}}">Duvidas</a></li>
                <li><a class="cabecalho" href="{{url_for('produto.home')}}">Produtos</a></li>
                <li><a class="cabecalho" href="about_us.html">Sobre nós</a></li>
                <li><a class="cabecalho" href="{{url_for('usuario.logar')}}">logar</a><img src="{{url_for('static', filename='usuario.jpg')}}" alt="" width="20" height="20"> </li>
                <li><a class="cabecalho" href="{{url_for('adm.home')}}">adm</a></li>
            </ul>
        </nav>
    </header>

    <!-- Exibir mensagens -->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}" role="alert">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <form class="formulario" action="{{url_for('produto.add')}}" method="post" enctype="multipart/form-data">
        <label for="tipo">Qual tipo de produto:</label><br>
            <input type="radio" name="tipo" id="brinquedo" value="brinquedo">
            <label for="brinquedo">BRINQUEDO</label><br>

            <input type="radio" name="tipo" id="petiscoC" value="petiscoC">
            <label for="petiscoC">PETISCO CACHORRO</label><br>

            <input type="radio" name="tipo" id="petiscoG" value="petiscoG">
            <label for="petiscoG">PETISCO GATO</label><br><br>

        <label for="nome">Nome do Produto: </label><br>
        <input type="text" name="nome" id="nome"><br><br>

        <label for="descricao">Descrição do Produto: </label><br>
        <input type="text" name="descricao" id="descricao"><br><br>

        <label for="preco">Preço do produto:</label><br>
        <input type="number" step="0.01" name="preco" min="0" id="preco"><br><br>

        <label for="disponivel">Tem Disponível:</label><br>
        <select name="disponivel" id="disponivel">
            <option value="sim">Sim</option>
            <option value="nao">Não</option>
        </select><br><br>

        <label for="imagem">Imagem:</label><br>
        <input type="file" name="imagem" id="imagem" accept="image/*"><br><br>

        <button type="submit" class="btn btn-primary">Adicionar</button>

    </form>
</body>
</html>

app/templates/duvidas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='layout.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>bichoito</title>
</head>
<body>
    <header>
        <img src="{{url_for('static', filename='BICHOITO.png')}}" class="bichoito">
        <nav>
            <ul>
                <li><a class="cabecalho" href="{{url_for('home.home')}}">Home</a></li>
                <li><a class="cabecalho" href="{{url_for('home.duvidas')}}">Duvidas</a></li>
                <li><a class="cabecalho" href="{{url_for('produto.home')}}">Produtos</a></li>
                <li><a class="cabecalho" href="about_us.html">Sobre nós</a></li>
                <li><a class="cabecalho" href="{{url_for('usuario.logar')}}">logar</a><img src="{{url_for('static', filename='usuario.jpg')}}" alt="" width="20" height="20"> </li>
                <li><a class="cabecalho" href="{{url_for('adm.home')}}">adm</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <a href="{{url_for('home.addDuvida')}}" class="botao">adicionar duvida</a><br>

        <h1>DUVIDAS</h1>
        <div class="caixa">
            {% for duvida in duvidas %}
            <div class="item">
                <h2>{{duvida.titulo}}</h2>
            </div>
            {% endfor %}
        </div>

    </main>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='layout.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>bichoito</title>
</head>
<body  style="background-color: rgb(253, 252, 233);">
    <header>
        <img src="{{url_for('static', filename='BICHOITO.png')}}" class="bichoito">
        <h1 class="title">{{nome}}</h1>
        <nav>
            <ul>
                <li><a class="cabecalho" href="{{url_for('home.home')}}">Home</a></li>
                <li><a class="cabecalho" href="{{url_for('home.duvidas')}}">Duvidas</a></li>
                <li><a class="cabecalho" href="{{url_for('produto.home')}}">Produtos</a></li>
                <li><a class="cabecalho" href="about_us.html">Sobre nós</a></li>
                <li><a class="cabecalho" href="{{url_for('usuario.logar')}}">logar</a><img src="{{url_for('static', filename='usuario.jpg')}}" alt="" width="20" height="20"> </li>
                <li><a class="cabecalho" href="{{url_for('adm.home')}}">adm</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <center>
        <h1>Bem vindo ao nosso Pet shop😼</h1>
        </center>
        <div>
            <img style="height: 75px; width:75px;" src="{{url_for('static', filename='cachorroFeliz.png')}}" alt="*imagem maneira de animais felizes">
        </div>
        <p></p>
        <p></p>
        <center>
            <div class="meio1">
                {% if logado == False %}
                <h4>sua primeira vez aqui? Faça seu cadastro aqui em baixo😁</h4>
                <a href="/usuario/cadastro" class="botao">cadastro</a>
                {% endif %}
            </div>
        </center>
    </main>
</body>
</html>

app/templates/listarTudo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='layout.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>bichoito</title>
</head>
<body>
    <header>
        <img src="{{url_for('static', filename='BICHOITO.png')}}" class="bichoito">
        <nav>
            <ul>
                <li><a class="cabecalho" href="{{url_for('home.home')}}">Home</a></li>
                <li><a class="cabecalho" href="{{url_for('home.duvidas')}}">Duvidas</a></li>
                <li><a class="cabecalho" href="{{url_for('produto.home')}}">Produtos</a></li>
                <li><a class="cabecalho" href="about_us.html">Sobre nós</a></li>
                <li><a class="cabecalho" href="{{url_for('usuario.logar')}}">logar</a><img src="{{url_for('static', filename='usuario.jpg')}}" alt="" width="20" height="20"> </li>
                <li><a class="cabecalho" href="{{url_for('adm.home')}}">adm</a></li>
            </ul>
        </nav>
    </header>
<main>

    <h1>LISTA dos USUARIOS</h1>
    <div class="caixa">
    {% for usuario in usuarios %}
        <a class="usuario" href="{{ url_for('usuario.update', usuario_id = usuario.id)}}" >
            <img src="{{ url_for('usuario.foto', usuario_id=usuario.id)}}
            "
            alt="Foto de {{ usuario.nome }}" class="foto_perfil">
            <p>{{ usuario.nome }}</p>
        </a>
    {% endfor %}
    </div>

    <br>

    <h1>LISTA dos PETISCOS PARA CACHORRO</h1>    
    <div class="caixa">
    {% for produto in produtosCachorro %}
    <a class="item" href="{{ url_for('produto.update', produto_id = produto.id)}}">
        <img src="{{ url_for('produto.foto', produto_id = produto.id)}}" alt="" class="foto_produto">
        <p>{{produto.nome}}</p>
    </a>
    {% endfor %}
    </div>

    <br>

    <h1>LISTA dos PETISCOS PARA GATO</h1>
    <div class="caixa">
    {% for produto in produtosGato %}
    <a class="item" href="{{ url_for('produto.update', produto_id = produto.id)}}">
        <img src="{{url_for('produto.foto', produto_id = produto.id)}}" alt="" class="foto_produto">
        <p>{{produto.nome}}</p>
    </a>
    {% endfor %}
    </div>   
    
    <br>

    <h1>LISTA dos BRINQUEDOS</h1>
    <div class="caixa">
    {% for produto in produtosBrinquedo %}
    <a class="item" href="{{ url_for('produto.update', produto_id = produto.id)}}">
        <img src="{{url_for('produto.foto', produto_id = produto.id)}}" alt="" class="foto_produto">
        <p>{{produto.nome}}</p>
    </a>
    {% endfor %}
    </div>

    <br>

        <h1>DUVIDAS</h1>
        <div class="caixa">
            {% for duvida in duvidas %}
            <div class="item">
                <h2>{{duvida.titulo}}</h2>
            </div>
            {% endfor %}
        </div>
</main>
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='layout.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>Criar cadastro</title>
</head>
<body>
    <header>
        <img src="{{url_for('static', filename='BICHOITO.png')}}" class="bichoito">
        <nav>
            <ul>
                <li><a class="cabecalho" href="{{url_for('home.home')}}">Home</a></li>
                <li><a class="cabecalho" href="{{url_for('home.duvidas')}}">Duvidas</a></li>
                <li><a class="cabecalho" href="{{url_for('produto.home')}}">Produtos</a></li>
                <li><a class="cabecalho" href="about_us.html">Sobre nós</a></li>
                <li><a class="cabecalho" href="{{url_for('usuario.logar')}}">logar</a><img src="{{url_for('static', filename='usuario.jpg')}}" alt="" width="20" height="20"> </li>
                <li><a class="cabecalho" href="{{url_for('adm.home')}}">adm</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <div class="container mt-5">
            <h1>LOGAR</h1>
            <!-- Exibir mensagens -->
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            <form action="{{url_for('usuario.logar')}}" method="post">
                <label for="email">Email</label><br>
                <input type="text" name="email" id="email"><br><br>

                <label for="senha">Senha</label><br>
                <input type="password" name="senha" id="senha"><br><br>

            <div class="field">
                <label class="checkbox">
                    <input type="checkbox">
                    Remember me
                </label>
            </div>

                <button type="submit" class="btn btn-primary">ENTRAR</button>

            </form>
        </div>
    </main>
</body>
</html>

app/templates/rotaADM.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='layout.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>ADM</title>
</head>
<body>
    <header>
        <img src="{{url_for('static', filename='BICHOITO.png')}}" class="bichoito">
        <nav>
            <ul>
                <li><a class="cabecalho" href="{{url_for('home.home')}}">Home</a></li>
                <li><a class="cabecalho" href="{{url_for('home.duvidas')}}">Duvidas</a></li>
                <li><a class="cabecalho" href="{{url_for('produto.home')}}">Produtos</a></li>
                <li><a class="cabecalho" href="about_us.html">Sobre nós</a></li>
                <li><a class="cabecalho" href="{{url_for('usuario.logar')}}">logar</a><img src="{{url_for('static', filename='usuario.jpg')}}" alt="" width="20" height="20"> </li>
                <li><a class="cabecalho" href="{{url_for('adm.home')}}">adm</a></li>
            </ul>
        </nav>
    </header>
    <main>
    <h1>ESSE É O ADMINISTRADOR</h1>

    <a class="botao" href="{{url_for('adm.listar')}}">lista de tudo</a>

    <a class="botao" href="{{url_for('produto.add')}}">adicionar produtos</a>

    <a href="{{url_for('usuario.cadastro')}}" class="botao">adicionar usuario</a>
    
    <a href="{{url_for('home.addDuvida')}}" class="botao">adicionar duvida</a>
</main>
</body>
</html>

app/templates/updateUser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static',filename='layout.css') }}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>edit</title>
</head>
<body>
    <header>
        <img src="{{url_for('static', filename='BICHOITO.png')}}" class="bichoito">
        <nav>
            <ul>
                <li><a class="cabecalho" href="{{url_for('home.home')}}">Home</a></li>
                <li><a class="cabecalho" href="{{url_for('home.duvidas')}}">Duvidas</a></li>
                <li><a class="cabecalho" href="{{url_for('produto.home')}}">Produtos</a></li>
                <li><a class="cabecalho" href="about_us.html">Sobre nós</a></li>
                <li><a class="cabecalho" href="{{url_for('usuario.logar')}}">logar</a><img src="{{url_for('static', filename='usuario.jpg')}}" alt="" width="20" height="20"> </li>
                <li><a class="cabecalho" href="{{url_for('adm.home')}}">adm</a></li>
            </ul>
        </nav>
    </header>
    <main class="formulario">
    <div class="container mt-5">
        <h1>Editar</h1>
        <!-- Exibir mensagens -->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        <form action="{{url_for('usuario.update', usuario_id = usuario.id)}}" method="post" enctype="multipart/form-data">
            <label for="nome">Nome</label><br>
            <input type="text" name="nome" id="nome" value="{{usuario.nome}}"><br><br>

            <label for="email">Email</label><br>
            <input type="text" name="email" id="email" value="{{usuario.email}}"><br><br>

            <label for="senha">Senha</label><br>
            <input type="password" name="senha" id="senha" value="{{usuario.senha}}"><br><br>

            <label for="foto_perfil">Foto de Perfil</label><br>
            <input type="file" name="foto_perfil" id="foto_perfil" accept="image/*" value="{{usuario.foto_perfil}}"><br><br>
            

            <button type="submit" class="btn btn-primary">Atualizar</button>
            
        </form>
        <form action="{{url_for('usuario.delete', usuario_id = usuario.id)}}" method="post">
            <button type="submit" class="btn btn-danger">APAGAR</button>
        </form>
        </main>
</body>
</html>